language: objective-c
rvm: system
install:
  # We are installing and testing homebrew, so we should uninstall everything
  - brew cask list
  - brew cask zap $(brew cask list)
  - brew list
  - brew uninstall --force $(brew list)
  - ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"

  # We are testing installation of Rubies, so should uninstall everything
  - rvm implode --force

  - export GEM_HOME=tmp/ruby/2.0.0/
  - export GEM_PATH=tmp/ruby/2.0.0/
  - export PATH=${GEM_HOME}/bin:${PATH}
  - gem install bundler --no-document
  - bundle install
script:
  - bundle exec rake ci
